
AWSTemplateFormatVersion : '2010-09-09'
Transform: 
    - AWS::Serverless-2016-10-31

Description: Lambda CloudFormation Lab
Resources:
    MyLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda.handler
            Runtime: python3.6
            CodeUri: src/